/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin-home',
    path: '/admin-home',
    component: 'layout.base$view.admin-home',
    meta: {
      title: 'admin-home',
      i18nKey: 'route.admin-home',
      hideInMenu: true
    }
  },
  {
    name: 'api-docs',
    path: '/api-docs',
    component: 'layout.base$view.api-docs',
    meta: {
      title: 'api-docs',
      i18nKey: 'route.api-docs',
      icon: 'mdi:file-document-outline',
      order: 7
    }
  },
  {
    name: 'api-key',
    path: '/api-key',
    component: 'layout.base$view.api-key',
    meta: {
      title: 'api-key',
      i18nKey: 'route.api-key',
      icon: 'mdi:key-variant',
      order: 6
    }
  },
  {
    name: 'device-manage',
    path: '/device-manage',
    component: 'layout.base$view.device-manage',
    meta: {
      title: 'device-manage',
      i18nKey: 'route.device-manage',
      icon: 'mdi:cellphone-link',
      order: 5,
      roles: ['admin']
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'jingdou-detail',
    path: '/jingdou-detail',
    component: 'layout.base$view.jingdou-detail',
    meta: {
      title: 'jingdou-detail',
      i18nKey: 'route.jingdou-detail',
      icon: 'mdi:wallet-outline',
      order: 3
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'proxy-manage',
    path: '/proxy-manage',
    component: 'layout.base$view.proxy-manage',
    meta: {
      title: 'proxy-manage',
      i18nKey: 'route.proxy-manage',
      icon: 'mdi:ip-network',
      order: 5.5,
      roles: ['admin']
    }
  },
  {
    name: 'system-settings',
    path: '/system-settings',
    component: 'layout.base$view.system-settings',
    meta: {
      title: 'system-settings',
      i18nKey: 'route.system-settings',
      icon: 'mdi:cog-outline',
      order: 8,
      roles: ['admin']
    }
  },
  {
    name: 'task-manage',
    path: '/task-manage',
    component: 'layout.base$view.task-manage',
    meta: {
      title: 'task-manage',
      i18nKey: 'route.task-manage',
      icon: 'mdi:clipboard-list-outline',
      order: 2
    }
  },
  {
    name: 'user-manage',
    path: '/user-manage',
    component: 'layout.base$view.user-manage',
    meta: {
      title: 'user-manage',
      i18nKey: 'route.user-manage',
      icon: 'mdi:account-group',
      order: 4,
      roles: ['admin']
    }
  }
];
